### ISSUE TITLE
A parameter cannot be found that matches parameter name SkipCertificateCheck

### ISSUE THREAD

**Issue by arnekos** [mmcelreath/PSSaltApi#3]
On powershell 5.1.17763.3770

When using the following:

$SuccessFullSaltMasterConnection = Connect-SaltApi -Server $SaltMaster -Port $Port -eAuthSystem pam -Credential $Credential -SkipCertificateCheck -Verbose

I get the following error:

Connect-SaltApi : Failure connecting to FakeServerName. A parameter cannot be found that matches parameter name 'SkipCertificateCheck'.

I don't get this error when I use powershell 7.2.6

**Comment by mmcelreath** [comment]
I'll check it out when I get a chance. Probably an issue with the version check for PowerShell.

**Comment by mmcelreath** [comment]
Just published some changes that should fix this issue. Let me know if you still have problems.
